### ISSUE TITLE
0.5.2

### ISSUE THREAD

**Issue by hultberg** [hultberg/rekaslife#52]
Next patch version

- [x] Config for displaying lead paragraph #54  
- [x] Unable to delete pages #50 
- [x] Textoverflow on date #51
- [x] Fix media thumbnails #53 
- [x] Remove container-fluid on navbar #55

**Comment by hultberg** [comment]
Almost ready for release, must fix tests first.

**Comment by hultberg** [comment]
Released
